### ISSUE TITLE
undefined method `*' for nil:NilClass / Location controller search action.

### ISSUE THREAD

**Issue by yoshi522** [manma-co/kazoku-db-system#7]
Log
``` 
Started GET "/locations/search?utf8=%E2%9C%93&address=%E5%B7%A3%E9%B4%A8&commit=%E6%A4%9C%E7%B4%A2" for ::1 at 2017-04-17 21:16:42 +0900
Processing by LocationsController#search as HTML
  Parameters: {"utf8"=>"✓", "address"=>"巣鴨", "commit"=>"検索"}
  Location Load (0.1ms)  SELECT "locations".* FROM "locations"
Completed 500 Internal Server Error in 614ms (ActiveRecord: 0.1ms)


  
NoMethodError (undefined method `*' for nil:NilClass):
  
app/models/location.rb:31:in `distance_of_two_points'
app/models/location.rb:21:in `block in candidate_list'
app/models/location.rb:15:in `candidate_list'
app/controllers/locations_controller.rb:23:in `search'

```

Solution

- [x] 家族登録用APIを使って保存する際にlocationの情報を入れるようにする。

- [x] Location tableのlatitudeとlongitudeをnilにならないようにvalidationをかける。

**Comment by yoshi522** [comment]
Done with d6b89e
